### PR TITLE
Refactor generic code

### PR DESCRIPTION
**Pull request by gusty**
This will work in F# 4.0 or lower.
It will also work if the reversion of my PR (1650) to the FSharp Compiler is again accepted.

### CODE REVIEW

**Comment by rspeele** [comment]
I am pretty busy this week and want to give this a real review, so it will probably be next weekend before I can get to it. Wanted to let you know I'm not ignoring it and am very interested to read how it works.

**Comment by gusty** [comment]
No worries. I'll see in the meantime if there is something else I can improve. Thanks for letting me know.

**Comment by rspeele** [comment]
Hey,

Neat technique with the overloads. I was concerned about a possible performance difference if things didn't get optimized out during inlining, but it seems to be even with the pre-patch version, so that's good!

I am going to go ahead and merge this to get back compat with F# 4.0. I will also be altering the header comment to mention your contribution. Thank you!

Regards,
Robert

**Comment by gusty** [comment]
Thanks for your feedback, I'm happy to help.

**Pull request merged**
