### PR TITLE
Support for netstandard2.0

### PR DESCRIPTION
**Pull request by isaacabraham**
This add *basic* support for netstandard2.0. I don't know what else is required - probably upping the version number and some other testing.

Linked to #29

### CODE REVIEW

**Comment by isaacabraham** [comment]
@slang25 @forki do you think that this is good to go? I've tested by created a local version of the package, it seemed to work with Paket at least.

I imagine a new version number needs to be set and perhaps some other things as well.

**Review by forki — APPROVED** [review]
LGTM

**Comment by slang25** [comment]
👍 Looks good

**Comment by isaacabraham** [comment]
I've tested this locally and it seems to work, although I had to delete the `Directory.Build.Props` file to get it to compile (I suspect that this is environmental). @rspeele assuming you're happy with this, what's the next step required to push it to nuget?

**Pull request merged**
